**Basic Python**

In [ ]:
# ctrl + / -> comment
# ctrl + enter -> run
print("Hello World", end=" ")
print("kedua")

name = "Dustin"
lastName = "Bijou Arasy"

umur = 10
# name = input()
print(name + " " + lastName)

print("Umur: " + format(umur, "d"))
print(f"Nama: {name}, umur: {umur}")

Hello World kedua
Dustin Bijou Arasy
Umur: 10
Nama: Dustin, umur: 10


**Operator**

In [ ]:
# + - * / += -=
# gak ada ++ --
# ** //

print(7%4)
print(format(5/3, ".2f"))
print(5//3)

print(6**3)

3
1.67
1
216
0.2999999999999998


**Selection & Repetition**

In [ ]:
# a = 10
# b = 11

# if(a == b):
#   print("a = b")

# elif(a < b):
#   print("a < b")

# else:
#   print("a != b")

# print("luar")

for i in range(0, 10, 2):
  print(i, end=" ")

print()

a = 10
while a>2:
  print(a, end=" ")
  a-= 1

0 2 4 6 8 
10 9 8 7 6 5 4 3 

**Function**

In [ ]:
def kalkulator(a, b):
  print(f"menghitung {a} {b}")
  pertambahan  = a + b

  if(a == 0):
    return 0
  
  kalkulator(a-1, b)
  # return pertambahan, a-b, a*b, a//b

kalkulator(5, 7)
# plus, minus, multi, bagi = kalkulator(5, 3)
# print(f"plus: {plus}, minus: {minus}, multi: {multi}, bagi: {bagi}")

menghitung 5 7
menghitung 4 7
menghitung 3 7
menghitung 2 7
menghitung 1 7
menghitung 0 7


**Numpy**

In [ ]:
import numpy as np

In [ ]:
listAngka = [1,2,3,4,5,6,7,8,9]

array1 = [
    [1,2],
    [3,4]
  ]

array2 = [
    [2,3],
    [5,7]
]

print(array1 + array2)

matrix1 = np.array(array1)
matrix2 = np.array(array2)

print(matrix1 * matrix2)
print(np.dot(matrix1, matrix2))

print(listAngka)

[[1, 2], [3, 4], [2, 3], [5, 7]]
[[ 2  6]
 [15 28]]
[[12 17]
 [26 37]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
listAngka = np.array(listAngka)

print(listAngka[3:7])

[4 5 6 7]
